### PR TITLE
fix blocks styling when withoutWrapper = true

### LINKED ISSUE #21: Layout styling is broken when withoutWrapper=true on <Message> component
Left is `withoutWrapper=true`. The layout of child blocks are not in a column.
Screenshot 2024-08-11 at 7 58 22 PM

### PR DESCRIPTION
**Pull request by StephenTangCook**
Fixes #21

### CODE REVIEW

File: src/message.tsx [hunk 1]
```diff
@@ -62,12 +62,16 @@ export const Message = (props: Props) => {
           ])}
           style={style}
         >
-          {blocks.map((block, i) => {
-            const element = getBlockComponent(block);
-            if (!element) return null;
+          <div className="flex flex-col w-full">
+            <div className="slack_blocks_to_jsx--blocks">
```
Comment (StephenTangCook) [inline src/message.tsx:66]: I'm adding the same non-wrapper elements as below, so they are consistent.
